name             'simple-nat'
maintainer       'Daily Kos'
maintainer_email 'tech-crew@dailykos.com'
license          'All rights reserved'
description      'Installs/Configures simple-nat-cookbook'
long_description 'Installs/Configures simple-nat-cookbook'
version          '0.1.0'

depends 'iptables-ng', '~> 2.2.5'
depends 'sysctl',      '~> 0.6.2'
